/**
 * timing.ts — the MASTER CLOCK.
 *
 * Every duration, cut and beat in this video is derived from the processed narration,
 * never from a guess. `data/narration-timing.json` is generated by tools/remap-timing.mjs
 * from the locked `voiceover-processed.wav`; nothing in src/ is allowed to invent a
 * timestamp that isn't anchored here.
 *
 * Scenes ask questions in SECONDS (`kw('twist')`) and get FRAMES back, so scene code
 * never hard-codes a frame number.
 */

import narrationTiming from '../../data/narration-timing.json';
import { VIDEO } from './style';

export type Phrase = {
  id: string;
  text: string;
  start: number;
  end: number;
  wordRange: [number, number];
};

export type Keyword = { start: number; end: number; wordIndex: number };
export type CaptionChunk = { text: string; words: string[]; start: number; end: number };
export type Word = { text: string; start: number; end: number };

export const TIMING = narrationTiming as unknown as {
  duration: number;
  fps: number;
  tempo: number;
  rawDuration: number;
  silenceRemoved: number;
  wordCount: number;
  phrases: Phrase[];
  keywords: Record<string, Keyword>;
  captions: CaptionChunk[];
  words: Word[];
};

/** Seconds -> frames (rounded to nearest frame). */
export const sec = (s: number): number => Math.round(s * VIDEO.fps);

/** Narration length in frames. */
export const NARRATION_FRAMES = sec(TIMING.duration);

/**
 * The video runs slightly past the last word so the final gag can land and hold
 * before the hard cut. This is the ONLY place the video's length differs from the
 * audio's, and it is additive — it never rescales narration timing.
 */
export const TAIL_HOLD_SECONDS = 1.15;
export const TOTAL_FRAMES = sec(TIMING.duration + TAIL_HOLD_SECONDS);

/** Look up a phrase (scene) by id. Throws loudly rather than silently returning 0. */
export function phrase(id: string): Phrase {
  const p = TIMING.phrases.find((x) => x.id === id);
  if (!p) throw new Error(`Unknown narration phrase "${id}"`);
  return p;
}

/** Keyword start time in SECONDS, on the processed-audio timeline. */
export function kwSec(id: string): number {
  const k = TIMING.keywords[id];
  if (!k) throw new Error(`Unknown narration keyword "${id}"`);
  return k.start;
}

/** Keyword start in FRAMES, absolute on the composition timeline. */
export function kw(id: string): number {
  return sec(kwSec(id));
}

/** Keyword end in FRAMES, absolute. */
export function kwEnd(id: string): number {
  const k = TIMING.keywords[id];
  if (!k) throw new Error(`Unknown narration keyword "${id}"`);
  return sec(k.end);
}

/**
 * Keyword position relative to a scene's own start — what scene components want,
 * because they render inside a <Sequence> whose frame 0 is the scene start.
 */
export function kwIn(sceneId: string, keyword: string): number {
  return kw(keyword) - SCENE_START[sceneId];
}

export type SceneSpan = {
  id: string;
  /** Absolute composition frame the scene takes over. */
  from: number;
  durationInFrames: number;
  narration: string;
};

/**
 * Contiguous scene spans covering the whole composition.
 *
 * Each scene runs from its own first spoken word until the NEXT scene's first word, so
 * there is never a gap where no scene is mounted. Scene 1 is pulled back to frame 0 —
 * the hook has to be on screen before the first syllable, not after it.
 */
export const SCENE_SPANS: SceneSpan[] = TIMING.phrases.map((p, i, all) => {
  const from = i === 0 ? 0 : sec(p.start);
  const to = i < all.length - 1 ? sec(all[i + 1].start) : TOTAL_FRAMES;
  return { id: p.id, from, durationInFrames: to - from, narration: p.text };
});

/** Absolute start frame of each scene, by id. */
export const SCENE_START: Record<string, number> = Object.fromEntries(
  SCENE_SPANS.map((s) => [s.id, s.from]),
);

/** Scene-relative frame for an absolute number of seconds. */
export function atIn(sceneId: string, seconds: number): number {
  return sec(seconds) - SCENE_START[sceneId];
}

/** Scene-relative frame, given an offset from the scene's first spoken word. */
export function afterSpeech(sceneId: string, seconds: number): number {
  return sec(phrase(sceneId).start + seconds) - SCENE_START[sceneId];
}
