/**
 * Sfx.tsx — sound effects, anchored to spoken words.
 *
 * Order is not negotiable and mirrors the rest of the pipeline: the narration was processed
 * and LOCKED first, the transcript came from that locked file, and only now do effects get
 * hung off those timestamps. Nothing here can move the narration.
 *
 * ------------------------------------------------------------------------- mix policy
 *
 * NARRATION ALWAYS WINS. It renders at unity; nothing in this table exceeds 0.30, and most
 * sit near 0.14. A sound effect that makes a viewer miss a word has cost more than it gave,
 * every time, without exception. The one place levels rise is where a cue lands in a genuine
 * pause and is carrying a punchline.
 *
 * DENSITY IS A FUNCTION OF THE SECTION. This is fourteen minutes, not forty seconds. An
 * effect every second would be exhausting by minute three and would flatten the sections that
 * are meant to feel different. So:
 *
 *   explanation      almost silent; a tick when a diagram element lands, nothing else
 *   mechanism        quiet clicks and paper, marking the steps of an argument
 *   comedy           denser and louder, because the density IS the comic timing
 *   turning points   one deliberate sound, alone, in space
 *
 * `assertDensity()` enforces the ceiling at module load rather than trusting judgement — it
 * is very easy to add "just one more" thirty times across a long edit and never notice that a
 * section has become noise.
 *
 * Every sound is procedurally generated by `tools/mryolk/make-sfx.mjs`. Original work, nothing
 * to license, nothing to attribute, nothing that can trip Content ID.
 */

import React from 'react';
import { Audio, Sequence, staticFile } from 'remotion';
import { FPS, WORDS, spanOf, wordMatches } from './clock';

type Sound =
  | 'pop' | 'tick' | 'whoosh' | 'ding' | 'cash' | 'paper' | 'stamp' | 'thud'
  | 'crack' | 'boing' | 'error' | 'vanish' | 'sparkle' | 'crash' | 'flush' | 'swell';

/**
 * Per-category ceilings.
 *
 * A category exists so that a level decision is made ONCE for a kind of sound rather than
 * re-argued at every one of the eighty-odd cue sites, where it would drift.
 */
const GAIN: Record<Sound, number> = {
  pop: 0.13,
  tick: 0.09,
  whoosh: 0.12,
  ding: 0.15,
  cash: 0.16,
  paper: 0.13,
  stamp: 0.18,
  thud: 0.18,
  crack: 0.24,
  boing: 0.20,
  error: 0.17,
  vanish: 0.14,
  sparkle: 0.12,
  crash: 0.26,
  flush: 0.30,
  swell: 0.08,
};

type Cue = { at: number; sound: Sound; gain?: number; note: string };

/** Absolute seconds of a word, for anchoring a cue. `off` nudges by seconds, not frames. */
const W = (from: number, to: number, word: string, nth = 1, off = 0): number => {
  const { start, end } = spanOf(from, to);
  let seen = 0;
  for (const w of WORDS) {
    if (w.start < start - 0.001 || w.end > end + 0.001) continue;
    // Same matcher the scenes use, so a cue and the visual it punctuates can never
    // disagree about which token counts as "the word".
    if (!wordMatches(w.text, word)) continue;
    seen += 1;
    if (seen === nth) return w.start + off;
  }
  throw new Error(`sfx anchor "${word}" #${nth} not spoken in segments ${from}..${to}`);
};

/**
 * The cue sheet.
 *
 * Each entry names the visual event it punctuates. If a line cannot name one, it does not
 * belong here — "the timeline felt empty" is the reason bad mixes exist.
 */
export const SFX_CUES: Cue[] = [
  /* ---- ch01: the disappearance. Comedy density, five hard beats. ---- */
  { at: W(1, 1, 'mortgage'), sound: 'paper', note: 'mortgage document slides in' },
  { at: W(2, 2, 'Gone'), sound: 'whoosh', note: 'mortgage struck out and thrown off screen' },
  { at: W(4, 4, 'Gone'), sound: 'whoosh', note: 'credit card bill thrown' },
  { at: W(6, 6, 'Gone'), sound: 'whoosh', note: 'student loan thrown' },
  { at: W(8, 8, 'Gone'), sound: 'whoosh', note: 'corporate debt thrown' },
  { at: W(10, 10, 'gone'), sound: 'boing', note: 'government debt thrown — the fifth, so it lands differently' },
  { at: W(12, 12, 'Congratulations'), sound: 'sparkle', note: 'celebration' },
  { at: W(13, 13, 'approximately'), sound: 'error', note: 'the turn: "for approximately five minutes"' },
  { at: W(14, 14, 'breaking'), sound: 'crack', note: 'the bank splits' },
  { at: W(16, 16, 'freeze'), sound: 'thud', note: 'construction window slams in' },
  { at: W(18, 18, 'panic'), sound: 'crash', gain: 0.2, note: 'investor panic, red arrow down' },
  { at: W(19, 19, 'screws', 1), sound: 'tick', note: 'the loose screw appears' },
  { at: W(21, 21, 'debt'), sound: 'stamp', note: 'THE MODERN WORLD RUNS ON DEBT lands' },

  /* ---- ch02: the mortgage. Mechanism density — paper and money, little else. ---- */
  { at: W(25, 25, 'thousand', 1), sound: 'pop', note: '$300,000 price appears on the house' },
  { at: W(27, 27, 'not'), sound: 'error', note: 'the wallet is empty' },
  { at: W(30, 30, 'gives'), sound: 'cash', note: 'the bank hands over the money' },
  { at: W(31, 31, 'mortgage'), sound: 'stamp', note: 'MORTGAGE contract stamped' },
  { at: W(36, 36, 'enough'), sound: 'ding', note: '"good enough" — the bank agrees' },
  { at: W(38, 38, 'machine'), sound: 'sparkle', note: 'the time machine portal opens' },

  /* ---- ch03: waiting is expensive. Ticking years, then the release. ---- */
  { at: W(48, 48, 'one'), sound: 'tick', note: 'year one appears on the timeline' },
  { at: W(49, 49, 'five'), sound: 'tick', note: 'year five' },
  { at: W(50, 50, 'twelve'), sound: 'tick', note: 'year twelve, the spreadsheet' },
  { at: W(51, 51, 'twenty'), sound: 'tick', note: 'year twenty' },
  { at: W(53, 53, 'competitor'), sound: 'error', note: 'the competitor already won' },
  { at: W(54, 54, 'borrow'), sound: 'cash', note: 'the loan arrives instead' },
  { at: W(55, 55, 'today', 1), sound: 'stamp', note: 'the factory is built today' },
  { at: W(60, 60, 'investment'), sound: 'ding', note: 'future productivity becomes present investment' },

  /* ---- ch04: banks create money. The balance sheet is the beat. ---- */
  { at: W(62, 62, 'vault'), sound: 'thud', note: 'the vault door swings open' },
  { at: W(64, 64, 'McDuck'), sound: 'boing', note: 'the Scrooge McDuck gag' },
  { at: W(67, 67, 'owe'), sound: 'paper', note: 'the loan lands on the asset side' },
  { at: W(67, 67, 'credited'), sound: 'cash', note: 'the deposit lands on the liability side' },
  { at: W(70, 70, 'liability'), sound: 'tick', note: 'the two entries are bracketed together' },
  { at: W(73, 73, 'Lamborghini'), sound: 'boing', note: 'the copy-paste joke' },
  { at: W(74, 74, 'back'), sound: 'error', note: 'borrowers occasionally do not pay back' },

  /* ---- ch05: who lends. Light — the diagram carries it. ---- */
  { at: W(81, 81, 'lending'), sound: 'pop', note: 'the question lands' },
  { at: W(82, 82, 'everyone'), sound: 'sparkle', note: 'the lender ring appears' },
  { at: W(89, 89, 'chat'), sound: 'ding', note: 'the group chat gag' },
  { at: W(90, 90, 'true'), sound: 'error', note: '...until you realise it has to be true' },

  /* ---- ch06: government bonds. The rollover gag is the payoff. ---- */
  { at: W(92, 92, 'bonds'), sound: 'paper', note: 'the bond is issued' },
  { at: W(93, 93, 'IOU'), sound: 'stamp', note: 'A BOND IS AN I.O.U.' },
  { at: W(98, 98, 'Banks'), sound: 'tick', note: 'first buyer' },
  { at: W(99, 99, 'Pension'), sound: 'tick', note: 'second buyer' },
  { at: W(100, 100, 'Investment'), sound: 'tick', note: 'third buyer' },
  { at: W(101, 101, 'Insurance'), sound: 'tick', note: 'fourth buyer' },
  { at: W(102, 102, 'Foreign'), sound: 'tick', note: 'fifth buyer' },
  { at: W(103, 103, 'central'), sound: 'ding', note: 'even central banks' },
  { at: W(110, 110, 'trillion'), sound: 'error', note: 'the enormous credit card bill gag' },
  { at: W(115, 115, 'matures'), sound: 'paper', note: 'first bond matures' },
  { at: W(117, 117, 'matures'), sound: 'paper', note: 'second bond matures' },
  { at: W(118, 118, 'bond'), sound: 'paper', note: 'and another' },
  { at: W(120, 120, 'Tuesday'), sound: 'boing', note: '"I\'ll pay you Tuesday"' },
  { at: W(123, 123, 'Tuesday'), sound: 'boing', gain: 0.24, note: '"how do you feel about NEXT Tuesday"' },

  /* ---- ch07: sustainability. Quiet — this is the reasoning section. ---- */
  { at: W(133, 133, 'thousand', 1), sound: 'tick', note: 'person A appears' },
  { at: W(134, 134, 'thousand', 1), sound: 'tick', note: 'person B appears' },
  { at: W(135, 135, 'panic'), sound: 'error', note: 'very different panic levels' },

  /* ---- ch08: productive or stupid. One gag, one sound. ---- */
  { at: W(140, 140, 'infrastructure'), sound: 'ding', note: 'the productive column' },
  { at: W(141, 141, 'golden'), sound: 'sparkle', note: 'the golden statue rises' },
  { at: W(141, 141, 'lasers'), sound: 'boing', note: 'shooting lasers from its eyes' },
  { at: W(143, 143, 'leverage'), sound: 'stamp', note: 'LEVERAGE lands' },

  /* ---- ch09: leverage. The arithmetic is the story; each figure gets a beat. ---- */
  { at: W(147, 147, 'ten'), sound: 'pop', note: '$10 appears' },
  { at: W(149, 149, 'dollar'), sound: 'cash', gain: 0.1, note: '+$1 — deliberately small' },
  { at: W(151, 151, 'coffee'), sound: 'tick', note: 'half a coffee' },
  { at: W(152, 152, 'ninety'), sound: 'cash', note: '+$90 borrowed' },
  { at: W(153, 153, 'hundred'), sound: 'stamp', note: '$100 total bet' },
  { at: W(155, 155, 'ten'), sound: 'ding', note: '+$10 gain' },
  { at: W(157, 157, 'incredible'), sound: 'sparkle', note: 'the smug moment' },
  { at: W(160, 160, 'yachts'), sound: 'boing', note: 'researching yachts' },
  { at: W(161, 161, 'falls'), sound: 'crash', note: 'the investment falls 10%' },
  { at: W(163, 163, 'gone'), sound: 'vanish', gain: 0.2, note: 'the original $10 is wiped out' },
  { at: W(164, 164, 'ninety'), sound: 'error', note: 'the lender still wants its $90' },

  /* ---- ch10: trust. A turning point — almost nothing, deliberately. ---- */
  { at: W(170, 170, 'Trust'), sound: 'swell', note: 'TRUST alone on white' },
  { at: W(178, 178, 'yes'), sound: 'ding', gain: 0.11, note: 'the YES gauge' },
  { at: W(179, 179, 'maybe'), sound: 'tick', note: 'the MAYBE gauge' },
  { at: W(180, 180, 'not'), sound: 'error', note: 'the ABSOLUTELY NOT gauge' },
  { at: W(181, 181, 'disappears'), sound: 'vanish', note: 'the money disappears' },

  /* ---- ch11: the crisis loop. Rising pressure, one turn at a time. ---- */
  { at: W(183, 183, 'higher'), sound: 'tick', note: 'rates rise, first turn of the loop' },
  { at: W(185, 185, 'again'), sound: 'tick', note: 'second turn' },
  { at: W(187, 187, 'Eventually'), sound: 'vanish', note: 'lenders stop entirely' },
  { at: W(192, 192, 'microphone'), sound: 'boing', note: 'the podcast microphone' },
  { at: W(192, 192, 'breaks'), sound: 'crack', note: 'then something breaks' },
  { at: W(193, 193, 'defaulting'), sound: 'crash', gain: 0.22, note: 'the cascade begins' },

  /* ---- ch12: 2008. Restrained. This section earns nothing from comedy. ---- */
  { at: W(197, 197, 'rising'), sound: 'tick', note: 'the housing price line climbs' },
  { at: W(200, 200, 'fell'), sound: 'crash', note: 'housing prices fall' },
  { at: W(203, 203, 'safe', 2), sound: 'error', note: 'things they thought were safe were not' },
  { at: W(204, 204, 'global'), sound: 'swell', note: 'the contagion spreads across the map' },

  /* ---- ch13: the counterfactual. ---- */
  { at: W(211, 211, 'it'), sound: 'pop', note: '"why not just get rid of it?"' },
  { at: W(214, 214, 'longer'), sound: 'tick', note: 'factories take longer' },
  { at: W(217, 217, 'harder'), sound: 'error', note: 'buying a house becomes harder' },
  { at: W(222, 222, 'bridge'), sound: 'ding', note: 'CREDIT IS THE BRIDGE' },

  /* ---- ch14: recession. The loop, then the flush. ---- */
  { at: W(224, 224, 'less'), sound: 'tick', note: 'spending falls' },
  { at: W(226, 226, 'workers'), sound: 'tick', note: 'layoffs' },
  { at: W(229, 229, 'fired'), sound: 'tick', note: 'the loop tightens' },
  { at: W(231, 231, 'flush'), sound: 'flush', note: 'the economic toilet flush' },
  { at: W(234, 234, 'borrow'), sound: 'cash', note: 'the government borrows to interrupt the loop' },

  /* ---- ch15: war and state power. Sober. ---- */
  { at: W(237, 237, 'bonds'), sound: 'stamp', note: 'WAR BONDS' },
  { at: W(238, 238, 'higher'), sound: 'error', note: 'the 300% tax alternative' },
  { at: W(241, 241, 'trust'), sound: 'swell', note: 'a government people trust enough to lend to' },

  /* ---- ch16-17: who we owe, and the network. ---- */
  { at: W(247, 247, 'Aliens'), sound: 'boing', note: 'aliens?' },
  { at: W(249, 249, 'Steve'), sound: 'ding', note: 'one extremely patient guy named Steve' },
  { at: W(250, 250, 'other'), sound: 'sparkle', note: 'mostly, we owe it to each other' },
  { at: W(256, 256, 'liability'), sound: 'stamp', note: 'YOUR ASSET IS SOMEONE ELSE\'S LIABILITY' },
  { at: W(259, 259, 'promises'), sound: 'swell', note: 'the network resolves' },
  { at: W(264, 264, 'waiting'), sound: 'tick', note: 'interest is the price of waiting' },
  { at: W(270, 270, 'stranger'), sound: 'sparkle', note: 'trust, expectations, promises' },
  { at: W(271, 271, 'celebrate'), sound: 'pop', note: 'the callback: he celebrates again' },
  { at: W(272, 272, 'minutes'), sound: 'boing', note: 'the five-minute timer starts' },
];

/**
 * Refuse a mix that has quietly become noise.
 *
 * Checked at module load so it fails the build rather than the render. The window is
 * generous — this only catches a section that has genuinely run away, not deliberate comic
 * clustering like the five "Gone" beats.
 */
function assertDensity(cues: Cue[]): void {
  const sorted = [...cues].sort((a, b) => a.at - b.at);
  const WINDOW = 10;
  const MAX_IN_WINDOW = 9;
  for (let i = 0; i < sorted.length; i++) {
    const n = sorted.filter((c) => c.at >= sorted[i].at && c.at < sorted[i].at + WINDOW).length;
    if (n > MAX_IN_WINDOW) {
      throw new Error(
        `${n} sound effects between ${sorted[i].at.toFixed(1)}s and ${(sorted[i].at + WINDOW).toFixed(1)}s `
        + `(ceiling is ${MAX_IN_WINDOW}). That is not punctuation any more.`,
      );
    }
  }
  for (const c of cues) {
    const g = c.gain ?? GAIN[c.sound];
    if (g > 0.32) throw new Error(`cue "${c.note}" at ${g} would compete with the narration`);
  }
}

assertDensity(SFX_CUES);

export const SfxTrack: React.FC = () => (
  <>
    {SFX_CUES.map((c, i) => (
      <Sequence key={`${c.sound}-${i}`} from={Math.max(0, Math.round(c.at * FPS))} name={`sfx:${c.sound}`}>
        <Audio src={staticFile(`mryolk/sfx/${c.sound}.wav`)} volume={c.gain ?? GAIN[c.sound]} />
      </Sequence>
    ))}
  </>
);
