/**
 * batch002/index.ts — the batch, as the renderer sees it.
 *
 * Same job as `registry.ts` does for Batch 001, with one difference: the scenes are DATA.
 * Each episode contributes a timing file, a storyboard, and a spec the DSL interprets, rather
 * than a hand-written module of React components.
 *
 * Imports are static and explicit rather than globbed for the reason the older registry gives:
 * Remotion bundles with esbuild, and a dynamic import would defeat both bundling and
 * type-checking. Generated by tools/batch-002-episodes.mjs conventions; edited by hand is fine.
 */

import type { NarrationTiming } from '../../lib/clock';
import type { EpisodeSpec } from '../../scenes/dsl';
import type { Storyboard } from '../registry';

import tapeMeasureHookTiming from '../../../episodes/tape-measure-hook/narration-timing.json';
import windshieldFritDotsTiming from '../../../episodes/windshield-frit-dots/narration-timing.json';
import coinReededEdgesTiming from '../../../episodes/coin-reeded-edges/narration-timing.json';
import foilShinyDullTiming from '../../../episodes/foil-shiny-dull/narration-timing.json';
import tactilePavingTiming from '../../../episodes/tactile-paving/narration-timing.json';
import airplaneAshtrayTiming from '../../../episodes/airplane-ashtray/narration-timing.json';
import thirdBrakeLightTiming from '../../../episodes/third-brake-light/narration-timing.json';
import sneakerLaceLockTiming from '../../../episodes/sneaker-lace-lock/narration-timing.json';
import padlockDrainHoleTiming from '../../../episodes/padlock-drain-hole/narration-timing.json';
import ferriteChokeTiming from '../../../episodes/ferrite-choke/narration-timing.json';
import brickHolesTiming from '../../../episodes/brick-holes/narration-timing.json';
import railwayBallastTiming from '../../../episodes/railway-ballast/narration-timing.json';
import chipBagNitrogenTiming from '../../../episodes/chip-bag-nitrogen/narration-timing.json';
import toiletSeatGapTiming from '../../../episodes/toilet-seat-gap/narration-timing.json';
import sodaCanNeckTiming from '../../../episodes/soda-can-neck/narration-timing.json';
import revolvingDoorTiming from '../../../episodes/revolving-door/narration-timing.json';
import convexMirrorWarningTiming from '../../../episodes/convex-mirror-warning/narration-timing.json';
import beerBottleBrownGlassTiming from '../../../episodes/beer-bottle-brown-glass/narration-timing.json';
import cabinLightsDimTiming from '../../../episodes/cabin-lights-dim/narration-timing.json';
import thermalReceiptFadeTiming from '../../../episodes/thermal-receipt-fade/narration-timing.json';

import tapeMeasureHookStory from '../../../episodes/tape-measure-hook/storyboard.json';
import windshieldFritDotsStory from '../../../episodes/windshield-frit-dots/storyboard.json';
import coinReededEdgesStory from '../../../episodes/coin-reeded-edges/storyboard.json';
import foilShinyDullStory from '../../../episodes/foil-shiny-dull/storyboard.json';
import tactilePavingStory from '../../../episodes/tactile-paving/storyboard.json';
import airplaneAshtrayStory from '../../../episodes/airplane-ashtray/storyboard.json';
import thirdBrakeLightStory from '../../../episodes/third-brake-light/storyboard.json';
import sneakerLaceLockStory from '../../../episodes/sneaker-lace-lock/storyboard.json';
import padlockDrainHoleStory from '../../../episodes/padlock-drain-hole/storyboard.json';
import ferriteChokeStory from '../../../episodes/ferrite-choke/storyboard.json';
import brickHolesStory from '../../../episodes/brick-holes/storyboard.json';
import railwayBallastStory from '../../../episodes/railway-ballast/storyboard.json';
import chipBagNitrogenStory from '../../../episodes/chip-bag-nitrogen/storyboard.json';
import toiletSeatGapStory from '../../../episodes/toilet-seat-gap/storyboard.json';
import sodaCanNeckStory from '../../../episodes/soda-can-neck/storyboard.json';
import revolvingDoorStory from '../../../episodes/revolving-door/storyboard.json';
import convexMirrorWarningStory from '../../../episodes/convex-mirror-warning/storyboard.json';
import beerBottleBrownGlassStory from '../../../episodes/beer-bottle-brown-glass/storyboard.json';
import cabinLightsDimStory from '../../../episodes/cabin-lights-dim/storyboard.json';
import thermalReceiptFadeStory from '../../../episodes/thermal-receipt-fade/storyboard.json';

import { spec as tapeMeasureHookSpec } from './tape-measure-hook';
import { spec as windshieldFritDotsSpec } from './windshield-frit-dots';
import { spec as coinReededEdgesSpec } from './coin-reeded-edges';
import { spec as foilShinyDullSpec } from './foil-shiny-dull';
import { spec as tactilePavingSpec } from './tactile-paving';
import { spec as airplaneAshtraySpec } from './airplane-ashtray';
import { spec as thirdBrakeLightSpec } from './third-brake-light';
import { spec as sneakerLaceLockSpec } from './sneaker-lace-lock';
import { spec as padlockDrainHoleSpec } from './padlock-drain-hole';
import { spec as ferriteChokeSpec } from './ferrite-choke';
import { spec as brickHolesSpec } from './brick-holes';
import { spec as railwayBallastSpec } from './railway-ballast';
import { spec as chipBagNitrogenSpec } from './chip-bag-nitrogen';
import { spec as toiletSeatGapSpec } from './toilet-seat-gap';
import { spec as sodaCanNeckSpec } from './soda-can-neck';
import { spec as revolvingDoorSpec } from './revolving-door';
import { spec as convexMirrorWarningSpec } from './convex-mirror-warning';
import { spec as beerBottleBrownGlassSpec } from './beer-bottle-brown-glass';
import { spec as cabinLightsDimSpec } from './cabin-lights-dim';
import { spec as thermalReceiptFadeSpec } from './thermal-receipt-fade';

/** Episode ids, in intended publication order. */
export const B2_ORDER = [
  'tape-measure-hook',
  'windshield-frit-dots',
  'coin-reeded-edges',
  'foil-shiny-dull',
  'tactile-paving',
  'airplane-ashtray',
  'third-brake-light',
  'sneaker-lace-lock',
  'padlock-drain-hole',
  'ferrite-choke',
  'brick-holes',
  'railway-ballast',
  'chip-bag-nitrogen',
  'toilet-seat-gap',
  'soda-can-neck',
  'revolving-door',
  'convex-mirror-warning',
  'beer-bottle-brown-glass',
  'cabin-lights-dim',
  'thermal-receipt-fade',
] as const;

export type Batch002Id = (typeof B2_ORDER)[number];

export const B2_TIMINGS: Record<Batch002Id, NarrationTiming> = {
  'tape-measure-hook': tapeMeasureHookTiming as NarrationTiming,
  'windshield-frit-dots': windshieldFritDotsTiming as NarrationTiming,
  'coin-reeded-edges': coinReededEdgesTiming as NarrationTiming,
  'foil-shiny-dull': foilShinyDullTiming as NarrationTiming,
  'tactile-paving': tactilePavingTiming as NarrationTiming,
  'airplane-ashtray': airplaneAshtrayTiming as NarrationTiming,
  'third-brake-light': thirdBrakeLightTiming as NarrationTiming,
  'sneaker-lace-lock': sneakerLaceLockTiming as NarrationTiming,
  'padlock-drain-hole': padlockDrainHoleTiming as NarrationTiming,
  'ferrite-choke': ferriteChokeTiming as NarrationTiming,
  'brick-holes': brickHolesTiming as NarrationTiming,
  'railway-ballast': railwayBallastTiming as NarrationTiming,
  'chip-bag-nitrogen': chipBagNitrogenTiming as NarrationTiming,
  'toilet-seat-gap': toiletSeatGapTiming as NarrationTiming,
  'soda-can-neck': sodaCanNeckTiming as NarrationTiming,
  'revolving-door': revolvingDoorTiming as NarrationTiming,
  'convex-mirror-warning': convexMirrorWarningTiming as NarrationTiming,
  'beer-bottle-brown-glass': beerBottleBrownGlassTiming as NarrationTiming,
  'cabin-lights-dim': cabinLightsDimTiming as NarrationTiming,
  'thermal-receipt-fade': thermalReceiptFadeTiming as NarrationTiming,
};

export const B2_STORYBOARDS: Record<Batch002Id, Storyboard> = {
  'tape-measure-hook': tapeMeasureHookStory as Storyboard,
  'windshield-frit-dots': windshieldFritDotsStory as Storyboard,
  'coin-reeded-edges': coinReededEdgesStory as Storyboard,
  'foil-shiny-dull': foilShinyDullStory as Storyboard,
  'tactile-paving': tactilePavingStory as Storyboard,
  'airplane-ashtray': airplaneAshtrayStory as Storyboard,
  'third-brake-light': thirdBrakeLightStory as Storyboard,
  'sneaker-lace-lock': sneakerLaceLockStory as Storyboard,
  'padlock-drain-hole': padlockDrainHoleStory as Storyboard,
  'ferrite-choke': ferriteChokeStory as Storyboard,
  'brick-holes': brickHolesStory as Storyboard,
  'railway-ballast': railwayBallastStory as Storyboard,
  'chip-bag-nitrogen': chipBagNitrogenStory as Storyboard,
  'toilet-seat-gap': toiletSeatGapStory as Storyboard,
  'soda-can-neck': sodaCanNeckStory as Storyboard,
  'revolving-door': revolvingDoorStory as Storyboard,
  'convex-mirror-warning': convexMirrorWarningStory as Storyboard,
  'beer-bottle-brown-glass': beerBottleBrownGlassStory as Storyboard,
  'cabin-lights-dim': cabinLightsDimStory as Storyboard,
  'thermal-receipt-fade': thermalReceiptFadeStory as Storyboard,
};

export const B2_SPECS: Record<Batch002Id, EpisodeSpec> = {
  'tape-measure-hook': tapeMeasureHookSpec,
  'windshield-frit-dots': windshieldFritDotsSpec,
  'coin-reeded-edges': coinReededEdgesSpec,
  'foil-shiny-dull': foilShinyDullSpec,
  'tactile-paving': tactilePavingSpec,
  'airplane-ashtray': airplaneAshtraySpec,
  'third-brake-light': thirdBrakeLightSpec,
  'sneaker-lace-lock': sneakerLaceLockSpec,
  'padlock-drain-hole': padlockDrainHoleSpec,
  'ferrite-choke': ferriteChokeSpec,
  'brick-holes': brickHolesSpec,
  'railway-ballast': railwayBallastSpec,
  'chip-bag-nitrogen': chipBagNitrogenSpec,
  'toilet-seat-gap': toiletSeatGapSpec,
  'soda-can-neck': sodaCanNeckSpec,
  'revolving-door': revolvingDoorSpec,
  'convex-mirror-warning': convexMirrorWarningSpec,
  'beer-bottle-brown-glass': beerBottleBrownGlassSpec,
  'cabin-lights-dim': cabinLightsDimSpec,
  'thermal-receipt-fade': thermalReceiptFadeSpec,
};
