/**
 * taxonomy.mjs — what each extracted drawing actually IS.
 *
 * The extractor can find 216 cells and cut them out perfectly, and it still has no idea which
 * one is a mortgage and which one is a yacht. That knowledge has to come from looking at the
 * sheets, so it is written down HERE, once, against the grid coordinate the extractor
 * produced — and every scene then addresses a drawing by meaning (`yolk.yacht-rich`) rather
 * than by position (`finance-b-r4c5`).
 *
 * That indirection is the whole point. Grid coordinates are an accident of how the art was
 * laid out; if a sheet is ever re-exported with the rows in a different order, only this file
 * changes and every scene keeps working. A scene that hardcoded `finance-b-r4c5` would
 * silently start showing a different drawing.
 *
 * Columns: [cell, slug, category, ...tags]
 *
 *   category  CHARACTER_EMOTION | NARRATIVE_ACTION | FINANCE_SCENE | FINANCE_PROP
 *             FINANCE_SCENE is a drawing where Mr.Yolk is WITH a prop; FINANCE_PROP is the
 *             object alone. The distinction matters constantly during the edit: a prop can be
 *             placed inside a diagram, and a scene cannot, because it already has an actor in
 *             it and two Mr.Yolks in one frame reads as a mistake.
 */

export const TAXONOMY = [
  /* ---------------------------------------------------- emote-a: face first */
  ['emote-a-r1c1', 'neutral-wave', 'CHARACTER_EMOTION', 'neutral', 'greeting'],
  ['emote-a-r1c2', 'happy-wave', 'CHARACTER_EMOTION', 'happy', 'greeting'],
  ['emote-a-r1c3', 'content-smile', 'CHARACTER_EMOTION', 'happy', 'calm'],
  ['emote-a-r1c4', 'excited-wave', 'CHARACTER_EMOTION', 'excited', 'greeting'],
  ['emote-a-r1c5', 'delighted-laugh', 'CHARACTER_EMOTION', 'happy', 'laughing'],
  ['emote-a-r1c6', 'laughing-hard', 'CHARACTER_EMOTION', 'laughing', 'joke'],
  ['emote-a-r2c1', 'cheering-arms-up', 'CHARACTER_EMOTION', 'celebrating', 'excited'],
  ['emote-a-r2c2', 'surprised-wide-eyes', 'CHARACTER_EMOTION', 'surprised'],
  ['emote-a-r2c3', 'shocked-mouth-open', 'CHARACTER_EMOTION', 'shocked'],
  ['emote-a-r2c4', 'gasp-small', 'CHARACTER_EMOTION', 'surprised', 'small'],
  ['emote-a-r2c5', 'flat-unimpressed', 'CHARACTER_EMOTION', 'deadpan', 'skeptical'],
  ['emote-a-r2c6', 'thinking-glance', 'CHARACTER_EMOTION', 'thinking'],
  ['emote-a-r3c1', 'skeptical-half-lidded', 'CHARACTER_EMOTION', 'skeptical'],
  ['emote-a-r3c2', 'unamused-frown', 'CHARACTER_EMOTION', 'skeptical', 'deadpan'],
  ['emote-a-r3c3', 'suspicious-side-eye', 'CHARACTER_EMOTION', 'skeptical', 'thinking'],
  ['emote-a-r3c4', 'grumpy-frown', 'CHARACTER_EMOTION', 'angry', 'small'],
  ['emote-a-r3c5', 'annoyed-frown', 'CHARACTER_EMOTION', 'angry'],
  ['emote-a-r3c6', 'displeased', 'CHARACTER_EMOTION', 'angry', 'skeptical'],
  ['emote-a-r4c1', 'angry-shouting', 'CHARACTER_EMOTION', 'angry', 'panic'],
  ['emote-a-r4c2', 'frustrated-wince', 'CHARACTER_EMOTION', 'angry', 'sad'],
  ['emote-a-r4c3', 'sad-worried', 'CHARACTER_EMOTION', 'sad', 'worried'],
  ['emote-a-r4c4', 'sad-downcast', 'CHARACTER_EMOTION', 'sad'],
  ['emote-a-r4c5', 'crying-tears', 'CHARACTER_EMOTION', 'crying', 'sad'],
  ['emote-a-r4c6', 'sobbing-wailing', 'CHARACTER_EMOTION', 'crying', 'panic'],
  ['emote-a-r5c1', 'scared-shocked', 'CHARACTER_EMOTION', 'shocked', 'panic'],
  ['emote-a-r5c2', 'terrified-scream', 'CHARACTER_EMOTION', 'panic', 'shocked'],
  ['emote-a-r5c3', 'nervous-fidget', 'CHARACTER_EMOTION', 'worried', 'nervous'],
  ['emote-a-r5c4', 'embarrassed-blush', 'CHARACTER_EMOTION', 'embarrassed'],
  ['emote-a-r5c5', 'bashful-blush', 'CHARACTER_EMOTION', 'embarrassed', 'shy'],
  ['emote-a-r5c6', 'sheepish-sad', 'CHARACTER_EMOTION', 'sad', 'embarrassed'],
  ['emote-a-r6c1', 'bored-half-lidded', 'CHARACTER_EMOTION', 'deadpan', 'bored'],
  ['emote-a-r6c2', 'winking-wave', 'CHARACTER_EMOTION', 'happy', 'smug'],
  ['emote-a-r6c3', 'playful-tongue-out', 'CHARACTER_EMOTION', 'happy', 'joke'],
  ['emote-a-r6c4', 'sleepy-eyes-closed', 'CHARACTER_EMOTION', 'sleeping', 'calm'],
  ['emote-a-r6c5', 'sly-smug-grin', 'CHARACTER_EMOTION', 'smug'],
  ['emote-a-r6c6', 'deadpan-blank', 'CHARACTER_EMOTION', 'deadpan', 'neutral'],

  /* --------------------------------------------- emote-b: whole-body reactions */
  ['emote-b-r1c1', 'neutral-small-smile', 'CHARACTER_EMOTION', 'neutral'],
  ['emote-b-r1c2', 'greeting-wave', 'CHARACTER_EMOTION', 'happy', 'greeting'],
  ['emote-b-r1c3', 'pointing-aside', 'NARRATIVE_ACTION', 'point', 'happy'],
  ['emote-b-r1c4', 'presenting-wide', 'NARRATIVE_ACTION', 'present', 'happy'],
  ['emote-b-r1c5', 'idea-raised-hand', 'CHARACTER_EMOTION', 'excited', 'idea'],
  ['emote-b-r1c6', 'dejected-pointing-down', 'CHARACTER_EMOTION', 'sad', 'point'],
  ['emote-b-r2c1', 'thinking-hand-on-chin', 'CHARACTER_EMOTION', 'thinking'],
  ['emote-b-r2c2', 'confused-question-mark', 'CHARACTER_EMOTION', 'confused', 'question'],
  ['emote-b-r2c3', 'shrug', 'CHARACTER_EMOTION', 'confused', 'shrug'],
  ['emote-b-r2c4', 'idea-sparkle', 'CHARACTER_EMOTION', 'excited', 'idea'],
  ['emote-b-r2c5', 'annoyed-arms-down', 'CHARACTER_EMOTION', 'angry', 'skeptical'],
  ['emote-b-r2c6', 'facepalm', 'CHARACTER_EMOTION', 'exasperated', 'joke'],
  ['emote-b-r3c1', 'startled', 'CHARACTER_EMOTION', 'surprised'],
  ['emote-b-r3c2', 'panic-shouting', 'CHARACTER_EMOTION', 'panic', 'shocked'],
  ['emote-b-r3c3', 'blank-stare-shock', 'CHARACTER_EMOTION', 'shocked', 'deadpan'],
  ['emote-b-r3c4', 'alarmed-arms-up', 'CHARACTER_EMOTION', 'panic', 'shocked'],
  ['emote-b-r3c5', 'worried-sweat', 'CHARACTER_EMOTION', 'worried'],
  ['emote-b-r3c6', 'anxious-shaking', 'CHARACTER_EMOTION', 'worried', 'panic'],
  ['emote-b-r4c1', 'deadpan-flat', 'CHARACTER_EMOTION', 'deadpan'],
  ['emote-b-r4c2', 'grumpy-arms-crossed', 'CHARACTER_EMOTION', 'skeptical', 'angry'],
  ['emote-b-r4c3', 'angry-clenched', 'CHARACTER_EMOTION', 'angry'],
  ['emote-b-r4c4', 'determined-flex', 'CHARACTER_EMOTION', 'determined'],
  ['emote-b-r4c5', 'disappointed-sigh', 'CHARACTER_EMOTION', 'sad', 'deadpan'],
  ['emote-b-r4c6', 'bawling', 'CHARACTER_EMOTION', 'crying'],
  ['emote-b-r5c1', 'happy-open-mouth', 'CHARACTER_EMOTION', 'happy'],
  ['emote-b-r5c2', 'excited-cheer', 'CHARACTER_EMOTION', 'excited', 'celebrating'],
  ['emote-b-r5c3', 'celebrating-arms-up', 'CHARACTER_EMOTION', 'celebrating'],
  ['emote-b-r5c4', 'thumbs-up-wink', 'CHARACTER_EMOTION', 'happy', 'approval'],
  ['emote-b-r5c5', 'blissful-sparkle', 'CHARACTER_EMOTION', 'happy', 'calm'],
  ['emote-b-r5c6', 'rolling-laughing', 'CHARACTER_EMOTION', 'laughing', 'joke'],
  ['emote-b-r6c1', 'walking-happy', 'NARRATIVE_ACTION', 'walk'],
  ['emote-b-r6c2', 'running', 'NARRATIVE_ACTION', 'run'],
  ['emote-b-r6c3', 'smug-arms-crossed', 'CHARACTER_EMOTION', 'smug'],
  ['emote-b-r6c4', 'leaping-excited', 'NARRATIVE_ACTION', 'jump', 'excited'],
  ['emote-b-r6c5', 'collapsed-exhausted', 'CHARACTER_EMOTION', 'exhausted', 'broke'],
  ['emote-b-r6c6', 'peeking-around-corner', 'NARRATIVE_ACTION', 'peek'],

  /* ------------------------------------------------ action: verbs and costumes */
  ['action-r1c1', 'reading-book', 'NARRATIVE_ACTION', 'read'],
  ['action-r1c2', 'reading-newspaper', 'NARRATIVE_ACTION', 'read', 'newspaper'],
  ['action-r1c3', 'magnifying-glass', 'NARRATIVE_ACTION', 'inspect'],
  ['action-r1c4', 'using-tablet', 'NARRATIVE_ACTION', 'phone', 'screen'],
  ['action-r1c5', 'using-laptop', 'NARRATIVE_ACTION', 'laptop', 'work'],
  ['action-r1c6', 'scientist-flask', 'NARRATIVE_ACTION', 'scientist', 'research'],
  ['action-r2c1', 'presenting-chart-board', 'NARRATIVE_ACTION', 'present', 'chart'],
  ['action-r2c2', 'reading-map', 'NARRATIVE_ACTION', 'map'],
  ['action-r2c3', 'holding-jar', 'NARRATIVE_ACTION', 'hold'],
  ['action-r2c4', 'measuring-ruler', 'NARRATIVE_ACTION', 'measure'],
  ['action-r2c5', 'planting-seed', 'NARRATIVE_ACTION', 'build', 'invest'],
  ['action-r2c6', 'telescope-looking', 'NARRATIVE_ACTION', 'inspect', 'future'],
  ['action-r3c1', 'pulling-rope', 'NARRATIVE_ACTION', 'pull', 'effort'],
  ['action-r3c2', 'pushing-wall', 'NARRATIVE_ACTION', 'push', 'effort'],
  ['action-r3c3', 'carrying-boulder', 'NARRATIVE_ACTION', 'carry', 'burden'],
  ['action-r3c4', 'digging-shovel', 'NARRATIVE_ACTION', 'dig', 'effort'],
  ['action-r3c5', 'climbing-rope', 'NARRATIVE_ACTION', 'climb', 'effort'],
  ['action-r3c6', 'running-away-scared', 'NARRATIVE_ACTION', 'run', 'panic'],
  ['action-r4c1', 'swimming', 'NARRATIVE_ACTION', 'swim'],
  ['action-r4c2', 'falling-down', 'NARRATIVE_ACTION', 'fall', 'panic'],
  ['action-r4c3', 'drowning-flailing', 'NARRATIVE_ACTION', 'swim', 'panic', 'burden'],
  ['action-r4c4', 'freezing-cold', 'NARRATIVE_ACTION', 'freeze'],
  ['action-r4c5', 'overheating-hot', 'NARRATIVE_ACTION', 'hot'],
  ['action-r4c6', 'hiding-under-table', 'NARRATIVE_ACTION', 'hide', 'panic'],
  ['action-r5c1', 'sick-ice-pack', 'NARRATIVE_ACTION', 'sick'],
  ['action-r5c2', 'dizzy-spiral-eyes', 'NARRATIVE_ACTION', 'sick', 'confused'],
  ['action-r5c3', 'sleeping-pillow', 'NARRATIVE_ACTION', 'sleep'],
  ['action-r5c4', 'eating-drumstick', 'NARRATIVE_ACTION', 'eat'],
  ['action-r5c5', 'drinking-cup', 'NARRATIVE_ACTION', 'drink'],
  ['action-r5c6', 'exhausted-panting', 'NARRATIVE_ACTION', 'exhausted'],
  ['action-r6c1', 'rich-money-bag', 'FINANCE_SCENE', 'rich', 'money-bag'],
  ['action-r6c2', 'broke-empty-pockets', 'FINANCE_SCENE', 'broke'],
  ['action-r6c3', 'king-crown-cape', 'NARRATIVE_ACTION', 'king', 'power'],
  ['action-r6c4', 'soldier-helmet-spear', 'NARRATIVE_ACTION', 'soldier', 'war'],
  ['action-r6c5', 'peasant-cloak', 'NARRATIVE_ACTION', 'peasant', 'history'],
  ['action-r6c6', 'astronaut-suit', 'NARRATIVE_ACTION', 'astronaut', 'aliens'],

  /* ------------------------------------- finance-a: the character WITH finance */
  ['finance-a-r1c1', 'waking-up-confused', 'FINANCE_SCENE', 'wake', 'question'],
  ['finance-a-r1c2', 'jumping-realisation', 'FINANCE_SCENE', 'excited', 'realise'],
  ['finance-a-r1c3', 'vanishing-outline', 'FINANCE_SCENE', 'disappear', 'debt-gone'],
  ['finance-a-r1c4', 'throwing-in-bin', 'FINANCE_SCENE', 'throw', 'debt-gone'],
  ['finance-a-r1c5', 'papers-flying-away-happy', 'FINANCE_SCENE', 'debt-gone', 'celebrating'],
  ['finance-a-r1c6', 'panicking-at-papers', 'FINANCE_SCENE', 'panic', 'past-due'],
  ['finance-a-r2c1', 'trapped-at-desk-panic', 'FINANCE_SCENE', 'panic', 'work'],
  ['finance-a-r2c2', 'closed-door-rejected', 'FINANCE_SCENE', 'rejected', 'no-credit'],
  ['finance-a-r2c3', 'construction-blocked', 'FINANCE_SCENE', 'construction', 'stalled'],
  ['finance-a-r2c4', 'opening-treasure-chest', 'FINANCE_SCENE', 'savings', 'excited'],
  ['finance-a-r2c5', 'holding-blank-paper-worried', 'FINANCE_SCENE', 'contract', 'worried'],
  ['finance-a-r2c6', 'airplane-screw-gag', 'FINANCE_SCENE', 'joke', 'airplane', 'removing-parts'],
  ['finance-a-r3c1', 'loving-the-house', 'FINANCE_SCENE', 'house', 'happy'],
  ['finance-a-r3c2', 'empty-wallet', 'FINANCE_SCENE', 'broke', 'wallet'],
  ['finance-a-r3c3', 'holding-document', 'FINANCE_SCENE', 'contract'],
  ['finance-a-r3c4', 'at-the-bank', 'FINANCE_SCENE', 'bank'],
  ['finance-a-r3c5', 'holding-cash-notes', 'FINANCE_SCENE', 'cash', 'happy'],
  ['finance-a-r3c6', 'handing-over-cash', 'FINANCE_SCENE', 'cash', 'pay'],
  ['finance-a-r4c1', 'meeting-future-self', 'FINANCE_SCENE', 'future-self', 'time'],
  ['finance-a-r4c2', 'sending-future-self-away', 'FINANCE_SCENE', 'future-self', 'time'],
  ['finance-a-r4c3', 'sitting-on-clock', 'FINANCE_SCENE', 'time', 'waiting'],
  ['finance-a-r4c4', 'factory-with-cash', 'FINANCE_SCENE', 'factory', 'invest'],
  ['finance-a-r4c5', 'airplane-with-cash', 'FINANCE_SCENE', 'airplane', 'invest'],
  ['finance-a-r4c6', 'tractor-with-cash', 'FINANCE_SCENE', 'farm', 'invest'],
  ['finance-a-r5c1', 'piggy-bank-saving', 'FINANCE_SCENE', 'saver', 'piggy-bank'],
  ['finance-a-r5c2', 'calendar-hourglass-waiting', 'FINANCE_SCENE', 'waiting', 'time'],
  ['finance-a-r5c3', 'holding-spreadsheet', 'FINANCE_SCENE', 'spreadsheet', 'plan'],
  ['finance-a-r5c4', 'factory-shock', 'FINANCE_SCENE', 'factory', 'shocked'],
  ['finance-a-r5c5', 'phone-shock', 'FINANCE_SCENE', 'phone', 'shocked'],
  ['finance-a-r5c6', 'government-building-worried', 'FINANCE_SCENE', 'government', 'worried'],
  ['finance-a-r6c1', 'at-the-vault', 'FINANCE_SCENE', 'bank', 'vault'],
  ['finance-a-r6c2', 'loan-approved-screen', 'FINANCE_SCENE', 'loan-approved', 'bank'],
  ['finance-a-r6c3', 'holding-price-tags', 'FINANCE_SCENE', 'prices', 'happy'],
  ['finance-a-r6c4', 'phone-stock-up', 'FINANCE_SCENE', 'invest', 'gains'],
  ['finance-a-r6c5', 'money-rain-rich', 'FINANCE_SCENE', 'rich', 'smug', 'gains'],
  ['finance-a-r6c6', 'past-due-crying', 'FINANCE_SCENE', 'past-due', 'crying'],

  /* ---------------------------- finance-b: bonds, leverage, trust, the crisis */
  ['finance-b-r1c1', 'shrug-empty-hands', 'CHARACTER_EMOTION', 'shrug', 'question'],
  ['finance-b-r1c2', 'retirement-fund', 'FINANCE_SCENE', 'lender', 'retirement', 'saver'],
  ['finance-b-r1c3', 'bank-holding-bond', 'FINANCE_SCENE', 'lender', 'bank', 'bond'],
  ['finance-b-r1c4', 'insurance-company', 'FINANCE_SCENE', 'lender', 'insurer'],
  ['finance-b-r1c5', 'investor-with-flag', 'FINANCE_SCENE', 'lender', 'investor'],
  ['finance-b-r1c6', 'money-circulation-cycle', 'FINANCE_SCENE', 'diagram', 'circulation'],
  ['finance-b-r2c1', 'government-issuing-bond', 'FINANCE_SCENE', 'government', 'bond'],
  ['finance-b-r2c2', 'holding-government-iou', 'FINANCE_SCENE', 'government', 'iou'],
  ['finance-b-r2c3', 'hugging-safe-bond', 'FINANCE_SCENE', 'bond', 'safe', 'happy'],
  ['finance-b-r2c4', 'bond-as-collateral', 'FINANCE_SCENE', 'bond', 'collateral'],
  ['finance-b-r2c5', 'government-bill-huge', 'FINANCE_SCENE', 'government', 'debt'],
  ['finance-b-r2c6', 'rollover-old-iou-new-iou', 'FINANCE_SCENE', 'rollover', 'iou', 'joke'],
  ['finance-b-r3c1', 'medal-award', 'FINANCE_SCENE', 'reward', 'happy'],
  ['finance-b-r3c2', 'empty-pockets-sad', 'FINANCE_SCENE', 'broke', 'sad'],
  ['finance-b-r3c3', 'bridge-and-road', 'FINANCE_SCENE', 'infrastructure', 'productive'],
  ['finance-b-r3c4', 'new-factory-sparkle', 'FINANCE_SCENE', 'factory', 'productive'],
  ['finance-b-r3c5', 'golden-statue', 'FINANCE_SCENE', 'joke', 'stupid-debt', 'vanity'],
  ['finance-b-r3c6', 'confused-clipboard', 'FINANCE_SCENE', 'confused', 'question'],
  ['finance-b-r4c1', 'small-coin-stack', 'FINANCE_SCENE', 'equity', 'small'],
  ['finance-b-r4c2', 'growth-arrow-celebrate', 'FINANCE_SCENE', 'gains', 'celebrating'],
  ['finance-b-r4c3', 'carrying-loan-bag', 'FINANCE_SCENE', 'leverage', 'borrow'],
  ['finance-b-r4c4', 'smug-sunglasses', 'FINANCE_SCENE', 'smug', 'gains'],
  ['finance-b-r4c5', 'yacht-rich', 'FINANCE_SCENE', 'joke', 'yacht', 'rich'],
  ['finance-b-r4c6', 'crash-arrow-panic', 'FINANCE_SCENE', 'losses', 'panic', 'crash'],
  ['finance-b-r5c1', 'whispering-trust', 'FINANCE_SCENE', 'trust', 'rumour'],
  ['finance-b-r5c2', 'skeptical-doubt', 'CHARACTER_EMOTION', 'skeptical', 'trust'],
  ['finance-b-r5c3', 'rising-interest-rates', 'FINANCE_SCENE', 'interest-rate', 'panic'],
  ['finance-b-r5c4', 'cant-refinance', 'FINANCE_SCENE', 'no-credit', 'panic'],
  ['finance-b-r5c5', 'credit-disappears', 'FINANCE_SCENE', 'no-credit', 'crisis'],
  ['finance-b-r5c6', 'collapsed-defeated', 'FINANCE_SCENE', 'crisis', 'broke'],
  ['finance-b-r6c1', 'house-prices-up', 'FINANCE_SCENE', 'house-prices', 'gains'],
  ['finance-b-r6c2', 'house-prices-down', 'FINANCE_SCENE', 'house-prices', 'crash', 'crying'],
  ['finance-b-r6c3', 'safe-assets-were-not', 'FINANCE_SCENE', 'crisis', '2008', 'panic'],
  ['finance-b-r6c4', 'toilet-flush-money', 'FINANCE_SCENE', 'joke', 'recession', 'flush'],
  ['finance-b-r6c5', 'war-bonds-soldier', 'FINANCE_SCENE', 'war', 'bond', 'history'],
  ['finance-b-r6c6', 'network-of-promises', 'FINANCE_SCENE', 'network', 'diagram', 'finale'],

  /* ------------------------------------------- props: objects, no character */
  ['props-r1c1', 'doc-mortgage', 'FINANCE_PROP', 'document', 'mortgage'],
  ['props-r1c2', 'doc-credit-card-bill', 'FINANCE_PROP', 'document', 'credit-card'],
  ['props-r1c3', 'doc-student-loan', 'FINANCE_PROP', 'document', 'student-loan'],
  ['props-r1c4', 'doc-corporate-debt', 'FINANCE_PROP', 'document', 'corporate-debt'],
  ['props-r1c5', 'doc-government-debt', 'FINANCE_PROP', 'document', 'government-debt'],
  ['props-r1c6', 'papers-flying', 'FINANCE_PROP', 'document', 'debt-gone'],
  ['props-r2c1', 'bank-building', 'FINANCE_PROP', 'bank'],
  ['props-r2c2', 'bank-broken', 'FINANCE_PROP', 'bank', 'crisis', 'broken'],
  ['props-r2c3', 'factory-smoking', 'FINANCE_PROP', 'factory', 'productive'],
  ['props-r2c4', 'construction-site', 'FINANCE_PROP', 'construction'],
  ['props-r2c5', 'treasure-chest', 'FINANCE_PROP', 'savings'],
  ['props-r2c6', 'airplane-losing-screw', 'FINANCE_PROP', 'joke', 'airplane'],
  ['props-r3c1', 'house', 'FINANCE_PROP', 'house'],
  ['props-r3c2', 'wallet-empty', 'FINANCE_PROP', 'wallet', 'broke'],
  ['props-r3c3', 'account-balance-zero', 'FINANCE_PROP', 'bank-account', 'broke'],
  ['props-r3c4', 'doc-paycheck', 'FINANCE_PROP', 'document', 'paycheck', 'income'],
  ['props-r3c5', 'doc-mortgage-contract', 'FINANCE_PROP', 'document', 'mortgage', 'contract'],
  ['props-r3c6', 'money-bag', 'FINANCE_PROP', 'money-bag', 'cash'],
  ['props-r4c1', 'clock', 'FINANCE_PROP', 'clock', 'time'],
  ['props-r4c2', 'money-through-time-portal', 'FINANCE_PROP', 'time-machine', 'cash', 'hero'],
  ['props-r4c3', 'piggy-bank', 'FINANCE_PROP', 'piggy-bank', 'saver'],
  ['props-r4c4', 'hourglass', 'FINANCE_PROP', 'hourglass', 'time'],
  ['props-r4c5', 'spreadsheet', 'FINANCE_PROP', 'spreadsheet', 'plan'],
  ['props-r4c6', 'factories-row', 'FINANCE_PROP', 'factory', 'industry'],
  ['props-r5c1', 'factory', 'FINANCE_PROP', 'factory'],
  ['props-r5c2', 'airplane', 'FINANCE_PROP', 'airplane'],
  ['props-r5c3', 'tractor', 'FINANCE_PROP', 'farm', 'tractor'],
  ['props-r5c4', 'road', 'FINANCE_PROP', 'infrastructure', 'road'],
  ['props-r5c5', 'doc-business-loan', 'FINANCE_PROP', 'document', 'business-loan'],
  ['props-r5c6', 'chart-growth', 'FINANCE_PROP', 'chart', 'gains'],
  ['props-r6c1', 'safe-vault', 'FINANCE_PROP', 'vault', 'bank'],
  ['props-r6c2', 'screen-loan-approved', 'FINANCE_PROP', 'loan-approved', 'screen'],
  ['props-r6c3', 'doc-loan', 'FINANCE_PROP', 'document', 'loan'],
  ['props-r6c4', 'doc-deposit', 'FINANCE_PROP', 'document', 'deposit'],
  ['props-r6c5', 'screen-bank-balance', 'FINANCE_PROP', 'bank-account', 'deposit', 'screen'],
  ['props-r6c6', 'doc-past-due', 'FINANCE_PROP', 'document', 'past-due', 'default'],
];
