/**
 * EpisodeSfx.tsx — sound effects, derived from the storyboard rather than hand-listed.
 *
 * Order is not negotiable: the voice was processed and LOCKED first, the timing was derived
 * from it, the storyboard was derived from that, and only now do effects get hung off those
 * timestamps. Nothing here can move the narration.
 *
 * Episode 001 hand-wrote ~35 cues against its keyword clock. Ten episodes would be 350 lines
 * of the same reasoning, so the mapping is inverted: every beat in the storyboard already
 * describes its own visual event in words ("pops in", "slams", "crossed out"), and those
 * verbs are exactly what choose a sound. One table serves the batch, and because beats are
 * keyword-anchored, reprocessing a narration re-times the SFX along with everything else.
 *
 * Beats that describe no audible event get no sound. Silence is the default — a Short whose
 * every beat clicks is exhausting, and the narration is the thing that must stay legible.
 *
 * Levels: narration renders at 1.0; nothing here exceeds 0.34, and the two beds sit lowest
 * of all — they are texture, not events. All sounds are procedurally generated by
 * tools/make-sfx.mjs: original work, nothing to license.
 */

import React from 'react';
import { Audio, Sequence, staticFile } from 'remotion';
import type { Storyboard } from '../episodes/registry';

type Rule = { test: RegExp; file: string; volume: number };

/**
 * First match wins, so the table is ordered most-specific first. A beat that both "slams in"
 * and "pops" should read as the slam.
 */
const RULES: Rule[] = [
  { test: /record[- ]scratch|hard cut:|hard interruption/i, file: 'record-scratch', volume: 0.3 },
  { test: /slams?|stamps?|snaps? (?:shut|in|onto)|clunk|thump|lands hard/i, file: 'impact', volume: 0.28 },
  { test: /camera punch|jolts|impact lines|drops straight down/i, file: 'impact', volume: 0.24 },
  { test: /\bclick\b|clicks|seats perfectly|valve shuts/i, file: 'tick', volume: 0.26 },
  { test: /crossed out|vanishe?s?|blinks out|pops out of existence|fades? to|blows away|dissolve/i, file: 'vanish', volume: 0.24 },
  { test: /sparkles?|glows?|blazes|lights up|spotlight|reveal/i, file: 'reveal-sting', volume: 0.2 },
  { test: /pops? (?:in|on|back)|pops\b|outlines?|labels?|circles? (?:teal|coral)/i, file: 'pop', volume: 0.2 },
  { test: /slides?|swings?|sweeps?|dives?|pulls? back|streams?|rolls?|whips?|yanked|drifts? past/i, file: 'whoosh', volume: 0.2 },
  { test: /ticks?|clock hands|counts?/i, file: 'tick', volume: 0.18 },
  { test: /rattles?|shuffles?|stacks? up|clutter|flakes?|dust/i, file: 'chip-clack', volume: 0.16 },
  { test: /flashes?|pulses?|flickers?|beeps?/i, file: 'blip', volume: 0.16 },
];

/** Beats that are purely a held expression or a look get nothing. */
const SILENT = /deadpan|looks at|watches|expression|blissful|content|nods?|stares?|thinks?|leans in/i;

export type SfxCue = { file: string; at: number; volume: number; note: string };

/** Derive the cue sheet for one episode. Pure — safe to memoise per storyboard. */
export function cuesFor(storyboard: Storyboard): SfxCue[] {
  const cues: SfxCue[] = [];
  let lastAt = -Infinity;

  const beats = storyboard.scenes
    .flatMap((s) => s.beats.map((b) => ({ ...b, scene: s.scene })))
    .sort((a, b) => a.t - b.t);

  for (const beat of beats) {
    if (SILENT.test(beat.action) && !/slams?|stamps?|pops?/i.test(beat.action)) continue;
    const rule = RULES.find((r) => r.test.test(beat.action));
    if (!rule) continue;
    // Two sounds inside 140 ms read as one messy noise, so the second is dropped.
    if (beat.t - lastAt < 0.14) continue;
    lastAt = beat.t;
    cues.push({ file: rule.file, at: beat.t, volume: rule.volume, note: `${beat.scene}: ${beat.action.slice(0, 60)}` });
  }

  return cues;
}

export const EpisodeSfx: React.FC<{ storyboard: Storyboard; fps: number }> = ({
  storyboard,
  fps,
}) => {
  const cues = React.useMemo(() => cuesFor(storyboard), [storyboard]);

  return (
    <>
      {cues.map((cue, i) => (
        <Sequence
          key={`${cue.file}-${i}`}
          from={Math.round(cue.at * fps)}
          name={`sfx:${cue.file} — ${cue.note}`}
        >
          <Audio src={staticFile(`sfx/${cue.file}.wav`)} volume={cue.volume} />
        </Sequence>
      ))}
    </>
  );
};
