/**
 * EpisodeSfx.tsx — sound effects, derived from the storyboard rather than hand-listed.
 *
 * Order is not negotiable: the voice was processed and LOCKED first, the timing was derived
 * from it, the storyboard was derived from that, and only now do effects get hung off those
 * timestamps. Nothing here can move the narration.
 *
 * Episode 001 hand-wrote ~35 cues against its keyword clock. Ten episodes would be 350 lines
 * of the same reasoning, so the mapping is inverted: every beat in the storyboard already
 * describes its own visual event in words ("pops in", "slams", "crossed out"), and those
 * verbs are exactly what choose a sound. One table serves the batch, and because beats are
 * keyword-anchored, reprocessing a narration re-times the SFX along with everything else.
 *
 * Beats that describe no audible event get no sound. Silence is the default — a Short whose
 * every beat clicks is exhausting, and the narration is the thing that must stay legible.
 *
 * LEVELS, and this was got wrong once. Narration renders at 1.0. The effects originally sat
 * at 0.15-0.30, which is 13-16 dB below the voice — present in the file, provably mixed by
 * the renderer, and effectively inaudible on a phone speaker. "Subtle" had become "not
 * there": the first person to watch a finished episode asked whether the SFX were missing,
 * and the honest answer was that they may as well have been.
 *
 * They now sit at 0.30-0.55, roughly 6 dB louder, which keeps the narration dominant by a
 * clear 7-10 dB while letting a slam actually land. Nothing exceeds 0.55, because a sound
 * that competes with the voice costs comprehension and the voice is the product.
 *
 * All sounds are procedurally generated by tools/make-sfx.mjs: original work, nothing to
 * license.
 */

import React from 'react';
import { Audio, Sequence, staticFile } from 'remotion';
import type { Storyboard } from '../episodes/registry';

type Rule = { test: RegExp; file: string; volume: number; weight: Weight };

/**
 * How much a sound is carrying.
 *
 * STRUCTURAL cues mark a story beat -- the slam, the reveal, the thing clicking shut. They
 * are the ones a viewer would miss.
 *
 * TEXTURE cues were doing atmospheric work: a flicker, a rattle, dust settling. The music bed
 * now does that job continuously and better, so keeping them means two things filling the
 * same space and a mix that never rests. They are dropped whenever an episode has a bed.
 */
type Weight = 'STRUCTURAL' | 'TEXTURE';

/** The brief asks for 2-6 meaningful effects per Short, and it is right to. */
const MAX_CUES = 6;

/**
 * First match wins, so the table is ordered most-specific first. A beat that both "slams in"
 * and "pops" should read as the slam.
 */
const RULES: Rule[] = [
  { test: /record[- ]scratch|hard cut:|hard interruption/i, file: 'record-scratch', volume: 0.55, weight: 'STRUCTURAL' },
  { test: /slams?|stamps?|snaps? (?:shut|in|onto)|clunk|thump|lands hard/i, file: 'impact', volume: 0.55, weight: 'STRUCTURAL' },
  { test: /camera punch|jolts|impact lines|drops straight down/i, file: 'impact', volume: 0.48, weight: 'STRUCTURAL' },
  { test: /\bclick\b|clicks|seats perfectly|valve shuts/i, file: 'tick', volume: 0.52, weight: 'STRUCTURAL' },
  { test: /crossed out|vanishe?s?|blinks out|pops out of existence|fades? to|blows away|dissolve/i, file: 'vanish', volume: 0.48, weight: 'STRUCTURAL' },
  { test: /sparkles?|glows?|blazes|lights up|spotlight|reveal/i, file: 'reveal-sting', volume: 0.4, weight: 'STRUCTURAL' },
  { test: /pops? (?:in|on|back)|pops\b|outlines?|labels?|circles? (?:teal|coral)/i, file: 'pop', volume: 0.4, weight: 'TEXTURE' },
  { test: /slides?|swings?|sweeps?|dives?|pulls? back|streams?|rolls?|whips?|yanked|drifts? past/i, file: 'whoosh', volume: 0.4, weight: 'STRUCTURAL' },
  { test: /ticks?|clock hands|counts?/i, file: 'tick', volume: 0.36, weight: 'TEXTURE' },
  { test: /rattles?|shuffles?|stacks? up|clutter|flakes?|dust/i, file: 'chip-clack', volume: 0.32, weight: 'TEXTURE' },
  { test: /flashes?|pulses?|flickers?|beeps?/i, file: 'blip', volume: 0.32, weight: 'TEXTURE' },

  /*
   * BATCH 002 VOCABULARY.
   *
   * The rules above were written by reading Batch 001's storyboards, where beats say "pops
   * in", "slams", "crossed out", "circles teal". Batch 002's beats describe the same KINDS of
   * event in different words -- "highlights", "draws in", "fills", "lights teal", "rotates" --
   * and matched almost none of them. The batch averaged 4.5 cues against Batch 001's 6.0, and
   * one episode got two.
   *
   * The fix belongs here rather than in the storyboards. This table is a map from "what the
   * picture does" to "what that sounds like", and a second batch simply extended the
   * vocabulary; rewording twenty storyboards so they match a regex would be writing the
   * script to suit the test. Every entry below is an event that genuinely makes a sound when
   * it happens on screen -- nothing was added to raise the count.
   */
  { test: /shatters?|splits? apart|cracks? (?:through|along)|punches? (?:in|through)/i, file: 'impact', volume: 0.52, weight: 'STRUCTURAL' },
  { test: /highlights?|lights? (?:teal|coral|gold|up)|lit\b|saturates?|brightens?/i, file: 'reveal-sting', volume: 0.4, weight: 'STRUCTURAL' },
  { test: /clamps?|locks? (?:against|closed|together)|wedges?|seizes?|cinches?|fuses?/i, file: 'tick', volume: 0.44, weight: 'STRUCTURAL' },
  { test: /rotates?|turns? (?:over|slowly|a|once)|spins?|peels? (?:away|apart|open)|separates?/i, file: 'whoosh', volume: 0.38, weight: 'STRUCTURAL' },
  { test: /drains?|floods?|pours?|escapes? (?:through|out)|feeds? through|travels? (?:through|with)/i, file: 'whoosh', volume: 0.36, weight: 'STRUCTURAL' },
  { test: /fills?\b|draws? in|redraws?|stamps? in|multiplies|form(?:s)? across/i, file: 'pop', volume: 0.36, weight: 'TEXTURE' },
  { test: /widens?|spreads?|blooms?|grades?|thins? (?:toward|out)|shrinks?/i, file: 'blip', volume: 0.3, weight: 'TEXTURE' },
];

/** Beats that are purely a held expression or a look get nothing. */
const SILENT = /deadpan|looks at|watches|expression|blissful|content|nods?|stares?|thinks?|leans in/i;

export type SfxCue = { file: string; at: number; volume: number; note: string; weight: Weight };

/**
 * Derive the cue sheet for one episode. Pure — safe to memoise per storyboard.
 *
 * `hasBed` matters: with music underneath, texture cues are covered and the effects that
 * remain should be the ones marking story beats. Without it, texture is all the atmosphere
 * the episode has, so it stays.
 */
export function cuesFor(storyboard: Storyboard, { hasBed = false } = {}): SfxCue[] {
  const found: SfxCue[] = [];
  let lastAt = -Infinity;

  const beats = storyboard.scenes
    .flatMap((s) => s.beats.map((b) => ({ ...b, scene: s.scene })))
    .sort((a, b) => a.t - b.t);

  for (const beat of beats) {
    if (SILENT.test(beat.action) && !/slams?|stamps?|pops?/i.test(beat.action)) continue;
    const rule = RULES.find((r) => r.test.test(beat.action));
    if (!rule) continue;
    if (hasBed && rule.weight === 'TEXTURE') continue;
    // Two sounds inside 140 ms read as one messy noise, so the second is dropped.
    if (beat.t - lastAt < 0.14) continue;
    lastAt = beat.t;
    found.push({
      file: rule.file, at: beat.t, volume: rule.volume, weight: rule.weight,
      note: `${beat.scene}: ${beat.action.slice(0, 60)}`,
    });
  }

  if (found.length <= MAX_CUES) return found;

  /*
   * Over budget. Volume in the rule table is already a judgement about how much a sound is
   * carrying -- a slam at 0.28 earns its place over a pop at 0.2 -- so it drives the ranking.
   *
   * But ranking on volume ALONE picks the same sound over and over: `impact` is the loudest
   * rule, and a straight sort left episodes with five impacts out of six, which is more
   * monotonous than the busy version it replaced. So each repeat of a sound already chosen
   * costs it, and cues too close to one already kept cost more. The result keeps the strong
   * beats while staying varied and spread out.
   */
  const kept: SfxCue[] = [];
  const remaining = [...found];

  while (kept.length < MAX_CUES && remaining.length) {
    let bestIdx = 0;
    let bestScore = -Infinity;
    for (let i = 0; i < remaining.length; i++) {
      const cue = remaining[i];
      const repeats = kept.filter((k) => k.file === cue.file).length;
      const crowded = kept.some((k) => Math.abs(k.at - cue.at) < 1.2);
      const score = cue.volume - repeats * 0.07 - (crowded ? 0.12 : 0);
      if (score > bestScore) { bestScore = score; bestIdx = i; }
    }
    kept.push(remaining.splice(bestIdx, 1)[0]);
  }

  return kept.sort((a, b) => a.at - b.at);
}

export const EpisodeSfx: React.FC<{ storyboard: Storyboard; fps: number; hasBed?: boolean }> = ({
  storyboard,
  fps,
  hasBed = false,
}) => {
  const cues = React.useMemo(() => cuesFor(storyboard, { hasBed }), [storyboard, hasBed]);

  return (
    <>
      {cues.map((cue, i) => (
        <Sequence
          key={`${cue.file}-${i}`}
          from={Math.round(cue.at * fps)}
          name={`sfx:${cue.file} — ${cue.note}`}
        >
          <Audio src={staticFile(`sfx/${cue.file}.wav`)} volume={cue.volume} />
        </Sequence>
      ))}
    </>
  );
};
