/**
 * SoundDesign.tsx — SFX placement, anchored to the same keyword clock as the visuals.
 *
 * Order matters and it is not negotiable: the voice was processed and LOCKED first, the
 * timing was derived from it, and only then do effects get hung off those timestamps.
 * Nothing here can move the narration.
 *
 * Levels: narration renders at 1.0; everything below is 0.10–0.34 so a sound can be felt
 * without ever masking a word. The two beds (light hum, swarm) sit lowest of all — they
 * are texture, not events.
 *
 * All sounds are procedurally generated by tools/make-sfx.mjs — original work, no
 * third-party audio, nothing to license.
 */

import React from 'react';
import { Audio, Sequence, staticFile } from 'remotion';
import { kwSec, sec, SCENE_START, phrase } from '../lib/timing';

type Cue = { file: string; at: number; volume: number; note: string };

/** Seconds -> a cue at that absolute time on the processed-audio timeline. */
const at = (file: string, seconds: number, volume: number, note: string): Cue => ({
  file,
  at: seconds,
  volume,
  note,
});

/** Scene-relative helper: `sceneAt('twist', 0.3)` = 0.3s after the twist scene starts. */
const sceneAt = (id: string, offset: number) => SCENE_START[id] / 30 + offset;

const CUES: Cue[] = [
  // --- hook ---
  at('pop', kwSec('casinos'), 0.22, 'casino sign lights up'),
  at('clock-pull', kwSec('clock'), 0.34, 'clock yanked off the wall'),
  at('impact', kwSec('clock'), 0.3, 'the theft lands'),
  at('pop', kwSec('clock') + 0.32, 0.2, 'question mark'),

  // --- no accident ---
  at('whoosh', phrase('no-accident').start, 0.18, 'culprit slides in'),
  at('blip', kwSec('accident'), 0.16, 'innocent smile'),

  // --- time cues: each removal gets the same sound, so the pattern is audible ---
  at('vanish', kwSec('clocks-vanish'), 0.26, 'clock removed'),
  at('vanish', kwSec('windows'), 0.26, 'window removed'),
  at('whoosh', kwSec('windows') + 0.73, 0.2, 'daylight slides away'),
  at('impact', kwSec('inside'), 0.26, 'the room closes in'),

  // --- constant environment ---
  at('light-hum', kwSec('lights'), 0.1, 'bed: an environment that never changes'),
  at('light-hum', kwSec('lights') + 2.4, 0.1, 'bed continues'),
  at('slot-beep', kwSec('flashing'), 0.24, 'machine flashes'),
  at('slot-beep', kwSec('flashing') + 0.62, 0.18, 'and again — nothing develops'),
  at('vanish', kwSec('disappears'), 0.24, 'outside world blinks out'),

  // --- time distortion ---
  at('clock-spin', kwSec('twenty-minutes') + 0.45, 0.26, 'hands accelerate'),
  at('impact', kwSec('two-hours'), 0.34, 'the reveal'),
  at('chip-clack', kwSec('two-hours') + 0.18, 0.16, 'the wreckage'),

  // --- twist ---
  at('record-scratch', kwSec('twist'), 0.32, 'hard interruption'),
  at('whoosh', kwSec('twist') + 0.3, 0.24, 'wipe to the bright casino'),

  // --- modern casino ---
  at('reveal-sting', kwSec('daylight'), 0.22, 'daylight reveal'),
  at('pop', kwSec('open-spaces'), 0.16, 'the room opens out'),
  at('tick', kwSec('clocks-modern'), 0.2, 'a clock, openly ticking'),
  at('tick', kwSec('clocks-modern') + 0.75, 0.15, 'still ticking'),

  // --- myth correction ---
  at('impact', kwSec('ban'), 0.28, 'NOT BANNED stamps down'),
  at('blip', kwSec('ban') + 0.95, 0.16, 'Bill spots the wristwatch'),

  // --- final idea ---
  at('chip-clack', kwSec('notice'), 0.2, 'distractions start'),
  at('money-flutter', kwSec('notice') + 0.3, 0.18, 'the wallet leaves'),
  at('chip-clack', kwSec('notice') + 0.7, 0.16, 'more distractions'),
  at('swarm', kwSec('immersed'), 0.14, 'bed: over-stimulation rising'),
  at('whoosh', kwSec('outside-world-2'), 0.22, 'camera rips back'),
  at('impact', kwSec('far-away'), 0.32, 'he turns; the wallet is gone'),
];

export const SoundDesign: React.FC = () => (
  <>
    {CUES.map((cue, i) => (
      <Sequence key={`${cue.file}-${i}`} from={sec(cue.at)} name={`sfx:${cue.file} — ${cue.note}`}>
        <Audio src={staticFile(`sfx/${cue.file}.wav`)} volume={cue.volume} />
      </Sequence>
    ))}
  </>
);

/** Exported for the audio-mix QA report. */
export const SFX_CUES = CUES;
export { sceneAt };
