/**
 * audio-plan.mts — write down what each episode's mix actually borrowed.
 *
 * The composition already knows: MUSIC_PLAN picks the bed and cuesFor derives the effects.
 * But the publish path is plain Node and cannot import a Remotion component, and a warning
 * about unverified licences is worthless if nothing populates the list it reads.
 *
 * So this exports the plan the renderer will use into `episodes/<id>/audio-plan.json`, from
 * the same modules the renderer imports. One source of truth, one portable artifact.
 *
 * The artifact carries NO absolute paths -- only asset ids and public-relative paths -- so it
 * stays portable. Where the packs live is a local fact and belongs in the database.
 *
 *   npx tsx tools/audio-plan.mts
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { cuesFor } from '../src/components/EpisodeSfx';
import { BEDS, MUSIC_PLAN } from '../src/components/EpisodeMusic';

const episodes = readdirSync('episodes').filter((e) => existsSync(join('episodes', e, 'storyboard.json')));
let total = 0;

console.log('\n  episode                bed                    sfx');
for (const id of episodes) {
  const storyboard = JSON.parse(readFileSync(join('episodes', id, 'storyboard.json'), 'utf8'));
  const bedId = (MUSIC_PLAN as Record<string, keyof typeof BEDS | null>)[id] ?? null;
  const cues = cuesFor(storyboard, { hasBed: Boolean(bedId) });

  const plan = {
    note: 'Generated by tools/audio-plan.mts from the same modules the renderer uses. '
      + 'Do not hand-edit; change MUSIC_PLAN or the SFX rules instead.',
    episode: id,
    music: bedId
      ? [{
        id: bedId,
        file: BEDS[bedId].file,
        seconds: BEDS[bedId].seconds,
        role: 'BED',
        // Never anything else. A downloaded pack with no licence metadata cannot be cleared
        // by the tool that reads it.
        provenance: 'USER_PROVIDED_UNKNOWN_LICENSE',
        mix: 'normalised to -30 LUFS; constant under speech, +4 dB in genuine pauses',
      }]
      : [],
    sfx: cues.map((c) => ({
      file: `sfx/${c.file}.wav`,
      at: Number(c.at.toFixed(3)),
      volume: c.volume,
      weight: c.weight,
      // These are generated by tools/make-sfx.mjs -- original work, nothing to license.
      provenance: 'GENERATED',
      note: c.note,
    })),
  };

  writeFileSync(join('episodes', id, 'audio-plan.json'), `${JSON.stringify(plan, null, 2)}\n`);
  total++;
  console.log(`  ${id.padEnd(22)} ${(bedId ?? 'none').padEnd(22)} ${cues.length}`);
}
console.log(`\n  wrote ${total} audio plans\n`);
